module.exports = {
  umdModuleIds: {
    '@angular/core': 'ng.core',
    '@angular/common/http': 'ng.common.http',
    '@ngrx/store': 'ngrx.store',
    'apollo-link': 'apolloLink.core',
    'apollo-client': 'apollo',
    'apollo-angular': 'ng.apollo',
    'apollo-angular-link-http': 'ng.apolloLink.http',
    'apollo-angular-link-http-common': 'ng.apolloLink.httpCommon',
    'apollo-cache-inmemory': 'apollo.cache.inmemory',
    'apollo-link-state': 'apolloLink.state',
    'apollo-link-error': 'apolloLink.error',
    'apollo-link-context': 'apolloLink.context',
    'apollo-link-batch': 'apolloLink.batch',
    'apollo-link-persisted-queries': 'persistedQueryLink',
    rxjs: 'rxjs',
    'rxjs/operators': 'rxjs.operators',
  },
};
