title: Apollo Angular
propertytitle: Using GraphQL in Angular
subtitle: Angular Guide
description: A guide to using the Apollo GraphQL Client with Angular.
versions:
  - '1'

sidebar_categories:
  null:
    - index
    - migration
  Basics:
    - basics/setup
    - basics/queries
    - basics/mutations
    - basics/network-layer
    - basics/caching
  Features:
    - features/error-handling
    - features/caching
    - features/optimistic-ui
    - features/cache-updates
    - features/fragments
    - features/developer-tooling
    - features/subscriptions
    - features/nativescript
    - features/multiple-clients
    - features/static-typing
  Recipes:
    - recipes/simple-example
    - recipes/query-splitting
    - recipes/pagination
    - recipes/authentication
    - recipes/prefetching
    - recipes/server-side-rendering
    - recipes/webpack
    - recipes/meteor
    - recipes/angular-cli

github_repo: apollographql/apollo-angular
content_root: docs/source

url: https://www.apollographql.com/docs/angular
root: /docs/angular/

public_dir: public/docs/angular
